name: fin_lit
services:
  web:
    build: .
    ports:
      - 5051:5000
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
volumes:
  db-data:
    driver: local