services:
  web:
    build: .
    image: python:3.8-slim-buster
    ports:
      - 5050:5000
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MARIADB_DATABASE=fin_lit=${DB_NAME}